---
title: "Day2_reproducible R"
author: "Marina e."
date: "9/15/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: yeti
    highlight: haddock
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Loading the data and libraries
```{r}
library(tidyverse)
```

# Pivots
```{r}
recall_df <- read_csv("~/github/rsdwr/data/repeated_measured_a.csv")
```
```{r}
recall_df_long <- pivot_longer(recall_df,
             cols = -Subject,
             names_to = "condtion",
             values_to = "score")
```

```{r}
pivot_wider(recall_df_long,
             names_from = "condtion",
             values_from = "score")
```

```{r}
recall_b_df <- read_csv("~/github/rsdwr/data/repeated_measured_b.csv")
```
```{r}
recall_b_df_long <- pivot_longer(recall_b_df,
            cols = -Subject,
            names_to ="condition",
            values_to = "score") 
```

# Separate and unite
```{r}
separate(recall_b_df_long, col = condition, 
         into = c("cued", "emotion"),
         sep = "_")
```
```{r}
pivot_longer(recall_b_df,
             cols = -Subject,
             names_to = c("cue", "emotion"),
             names_pattern = "(.*)_(.*)", #grouping expressions in regex, * mean matches at least one time
             values_to = "score")

#names_pattern = "(Free|Cued)_(Neg|Neu|Pos)"
```
```{r}
pivot_longer(recall_b_df,
             cols = -Subject,
             names_to = c("cue", "emotion"),
             names_sep = "_", #grouping expressions in regex, * mean matches at zero one time
             values_to = "score")

#class of separators names_sep = [_\\ . ;]
```

```{r}
blp_df <- read_csv("~/github/rsdwr/data/blp-trials-short.txt")


temp_df <- summarise_at(
  blp_df,
  vars(rt:rt.raw),
  list(
    ~ median(., na.rm = T),
    ~ mean(., na.rm = T),
    ~ sd(., na.rm = T)
  )
)
```

Now we want to pivot this table:
```{r}
pivot_longer(temp_df,
             cols = everything(),
             names_to = "var_desc",
             values_to ="result") %>% 
  separate(var_desc, into = c("var", "desc"), sep = "_") %>% 
  pivot_wider(names_from = "desc", values_from = "result")
```
We can do the same even faster!
```{r}
pivot_longer(temp_df,
             cols = everything(),
             names_to = c("var", ".value"), #.value is a command, for pivot longer
             names_pattern = "(.*)_(.*)")
```
```{r}
pivot_longer(temp_df,
             cols = everything(),
             names_to = c("var", "desc"),
             names_pattern = "(.*)_(.*)",
             values_to =  "result")
```
# Purrr: map
```{r}
my_list <- list(
  df_1 = tibble(x = rnorm(10)),
  df_2 = tibble(x = rnorm(5)),
  df_3 = tibble(x = rnorm(5))
)
```

```{r}
map(my_list, nrow)
map_dbl(my_list, nrow)
map_dbl(my_list, ~ mean(.x$x))
```
# Rownames in dataframes
Tibbles don't like rownames!
```{r}
mydf <- tibble(x = rnorm(3))
rownames(mydf) <- c("A", "B", "C")
```
What can we do?
```{r}
mydf_2 <- data.frame(x = rnorm(3)) 
rownames(mydf_2) <- c("A", "B", "C")
mydf_2 %>% as.tibble(rownames = "row_label")
```

Another way to do the same:
```{r}
rownames_to_column(mydf,"row_label")
```
```{r}

```

